name: 'superstore'
version: '1.0.0'
config-version: 2

profile: 'superstore'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  superstore:
    bronze:
      +materialized: table
    silver:
      +materialized: view
    gold:
      +materialized: table
    marts:
      +materialized: table
